-- ===========================
-- نظام الحضور والانصراف الكامل - مُصحح التوقيت والمُدمج
-- كود قاعدة البيانات المدمج والمُصحح للتوقيت العراقي
-- تشغيل هذا الكود في Supabase SQL Editor
-- مع حساب مدير مخفي واحد فقط
-- ===========================

-- 1. تفعيل الإضافات المطلوبة
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS postgis;

-- 2. حذف الجداول الموجودة وإعادة إنشائها
DROP TABLE IF EXISTS remote_commands CASCADE;
DROP TABLE IF EXISTS attendance_total CASCADE;
DROP TABLE IF EXISTS user_center_permissions CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS logs CASCADE;
DROP TABLE IF EXISTS employees CASCADE;
DROP TABLE IF EXISTS centers CASCADE;

-- 3. إنشاء جدول المراكز
CREATE TABLE centers (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    longitude DECIMAL(11, 8) NOT NULL,
    latitude DECIMAL(11, 8) NOT NULL,
    radius INTEGER NOT NULL DEFAULT 100,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. إنشاء جدول الموظفين
CREATE TABLE employees (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    phone VARCHAR(20) UNIQUE NOT NULL,
    password_hash TEXT,
    position VARCHAR(255) DEFAULT 'موظف',
    center_id INTEGER REFERENCES centers(id) ON DELETE SET NULL,
    status VARCHAR(20) DEFAULT 'inactive',
    failed_login_attempts INTEGER DEFAULT 0,
    locked_until TIMESTAMPTZ,
    last_login TIMESTAMPTZ,
    password_changed_at TIMESTAMPTZ DEFAULT NOW(),
    last_location_update TIMESTAMPTZ,
    auto_checkout_time TIMESTAMPTZ,
    location_timeout_minutes INTEGER DEFAULT 30,
    is_active BOOLEAN DEFAULT true,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. إنشاء جدول المستخدمين الإداريين
CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    phone VARCHAR(20),
    role VARCHAR(20) DEFAULT 'user',
    can_add_centers BOOLEAN DEFAULT true,
    can_add_employees BOOLEAN DEFAULT true,
    can_edit_centers BOOLEAN DEFAULT true,
    can_edit_employees BOOLEAN DEFAULT true,
    can_delete_centers BOOLEAN DEFAULT false,
    can_delete_employees BOOLEAN DEFAULT false,
    can_view_all_centers BOOLEAN DEFAULT false,
    can_view_all_employees BOOLEAN DEFAULT false,
    is_active BOOLEAN DEFAULT true,
    is_hidden BOOLEAN DEFAULT false, -- إضافة عمود لإخفاء المستخدمين
    failed_login_attempts INTEGER DEFAULT 0,
    locked_until TIMESTAMPTZ,
    last_login TIMESTAMPTZ,
    password_changed_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. إنشاء جدول صلاحيات المراكز للمستخدمين
CREATE TABLE user_center_permissions (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    center_id INTEGER REFERENCES centers(id) ON DELETE CASCADE,
    can_view BOOLEAN DEFAULT true,
    can_manage BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, center_id)
);

-- 7. إنشاء جدول السجلات
CREATE TABLE logs (
    id SERIAL PRIMARY KEY,
    employee_id INTEGER REFERENCES employees(id) ON DELETE CASCADE,
    center_id INTEGER REFERENCES centers(id) ON DELETE SET NULL,
    action VARCHAR(50) NOT NULL,
    latitude DECIMAL(11, 8),
    longitude DECIMAL(11, 8),
    accuracy DECIMAL(8, 2),
    device_info TEXT,
    notes TEXT,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7.1 إنشاء جدول سجل العمليات الرئيسية main_logs
CREATE TABLE IF NOT EXISTS main_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action TEXT,
    entity_type TEXT,
    entity_name TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    user_id UUID,
    occurred_at TIMESTAMPTZ DEFAULT NOW()
);

-- تأكد من وجود جميع الأعمدة المطلوبة بدون حذف بيانات (للتوافق مع أي تحديث سابق)
ALTER TABLE main_logs ADD COLUMN IF NOT EXISTS action TEXT;
ALTER TABLE main_logs ADD COLUMN IF NOT EXISTS entity_type TEXT;
ALTER TABLE main_logs ADD COLUMN IF NOT EXISTS entity_name TEXT;
ALTER TABLE main_logs ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE main_logs ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;
ALTER TABLE main_logs ADD COLUMN IF NOT EXISTS user_id UUID;
ALTER TABLE main_logs ADD COLUMN IF NOT EXISTS occurred_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE main_logs ADD COLUMN IF NOT EXISTS old_name TEXT;
ALTER TABLE main_logs ADD COLUMN IF NOT EXISTS new_name TEXT;

-- 8. إنشاء جدول عداد الحضور الإجمالي
CREATE TABLE attendance_total (
    id SERIAL PRIMARY KEY,
    total INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. إنشاء جدول الأوامر البعيدة
CREATE TABLE remote_commands (
    id SERIAL PRIMARY KEY,
    employee_id INTEGER REFERENCES employees(id) ON DELETE CASCADE,
    command TEXT NOT NULL,
    executed BOOLEAN DEFAULT false,
    executed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. إنشاء الفهارس
CREATE INDEX idx_employees_phone ON employees(phone);
CREATE INDEX idx_employees_center_id ON employees(center_id);
CREATE INDEX idx_employees_status ON employees(status);
CREATE INDEX idx_employees_last_location ON employees(last_location_update);
CREATE INDEX idx_employees_phone_active ON employees(phone, is_active);

CREATE INDEX idx_logs_employee_id ON logs(employee_id);
CREATE INDEX idx_logs_created_at ON logs(created_at);
CREATE INDEX idx_logs_occurred_at ON logs(occurred_at);
CREATE INDEX idx_logs_action ON logs(action);
CREATE INDEX idx_logs_employee_date ON logs(employee_id, created_at);
CREATE INDEX idx_logs_employee_occurred ON logs(employee_id, occurred_at);

CREATE INDEX idx_users_username ON users(username);
CREATE INDEX idx_users_role ON users(role);
CREATE INDEX idx_users_is_active ON users(is_active);
CREATE INDEX idx_users_is_hidden ON users(is_hidden);
CREATE INDEX idx_users_username_active ON users(username, is_active);

CREATE INDEX idx_user_center_permissions_user_id ON user_center_permissions(user_id);
CREATE INDEX idx_user_center_permissions_center_id ON user_center_permissions(center_id);

CREATE INDEX idx_centers_location ON centers(latitude, longitude);

CREATE INDEX idx_remote_commands_employee_id ON remote_commands(employee_id);
CREATE INDEX idx_remote_commands_executed ON remote_commands(executed);
CREATE INDEX idx_remote_commands_created_at ON remote_commands(created_at);

-- ===========================
-- دوال التوقيت المُصححة
-- ===========================

CREATE OR REPLACE FUNCTION get_iraq_time() 
RETURNS TIMESTAMPTZ AS $$
BEGIN
    RETURN NOW() AT TIME ZONE 'Asia/Baghdad';
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION format_iraq_time(input_time TIMESTAMPTZ)
RETURNS TEXT AS $$
BEGIN
    IF input_time IS NULL THEN
        RETURN 'غير محدد';
    END IF;
    RETURN to_char(input_time AT TIME ZONE 'Asia/Baghdad', 'YYYY-MM-DD HH24:MI:SS');
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_time_ago_arabic(input_time TIMESTAMPTZ)
RETURNS TEXT AS $$
DECLARE
    time_diff INTERVAL;
    seconds_diff INTEGER;
    minutes_diff INTEGER;
    hours_diff INTEGER;
    days_diff INTEGER;
BEGIN
    IF input_time IS NULL THEN
        RETURN 'غير محدد';
    END IF;
    
    time_diff := NOW() - input_time;
    seconds_diff := EXTRACT(epoch FROM time_diff)::INTEGER;
    
    IF seconds_diff < 30 THEN
        RETURN 'الآن';
    ELSIF seconds_diff < 60 THEN
        RETURN 'منذ لحظات';
    ELSIF seconds_diff < 3600 THEN
        minutes_diff := seconds_diff / 60;
        RETURN 'منذ ' || minutes_diff || ' دقيقة';
    ELSIF seconds_diff < 86400 THEN
        hours_diff := seconds_diff / 3600;
        RETURN 'منذ ' || hours_diff || ' ساعة';
    ELSE
        days_diff := seconds_diff / 86400;
        RETURN 'منذ ' || days_diff || ' يوم';
    END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ===========================
-- وظائف الأمان
-- ===========================

CREATE OR REPLACE FUNCTION validate_password(password TEXT) 
RETURNS JSON AS $$
BEGIN
    IF LENGTH(password) < 6 THEN
        RETURN json_build_object('valid', false, 'error', 'كلمة المرور يجب أن تكون 6 أحرف على الأقل');
    END IF;
    
    IF password ~ '^[0-9]+$' THEN
        RETURN json_build_object('valid', false, 'error', 'كلمة المرور يجب أن تحتوي على أحرف وليس أرقام فقط');
    END IF;
    
    RETURN json_build_object('valid', true);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION hash_password(password TEXT) 
RETURNS TEXT AS $$
DECLARE
    validation_result JSON;
BEGIN
    SELECT validate_password(password) INTO validation_result;
    
    IF NOT (validation_result->>'valid')::boolean THEN
        RAISE EXCEPTION '%', validation_result->>'error';
    END IF;
    
    RETURN crypt(password, gen_salt('bf', 12));
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION verify_password(password TEXT, password_hash TEXT) 
RETURNS BOOLEAN AS $$
BEGIN
    IF password_hash IS NULL OR password_hash = '' THEN
        RETURN FALSE;
    END IF;
    
    RETURN password_hash = crypt(password, password_hash);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION is_account_locked(emp_id INTEGER) 
RETURNS BOOLEAN AS $$
DECLARE
    emp_record RECORD;
BEGIN
    SELECT failed_login_attempts, locked_until
    INTO emp_record
    FROM employees 
    WHERE id = emp_id;
    
    IF NOT FOUND THEN
        RETURN FALSE;
    END IF;
    
    IF emp_record.locked_until IS NOT NULL AND emp_record.locked_until > NOW() THEN
        RETURN TRUE;
    END IF;
    
    IF emp_record.locked_until IS NOT NULL AND emp_record.locked_until <= NOW() THEN
        UPDATE employees 
        SET failed_login_attempts = 0, locked_until = NULL, updated_at = NOW()
        WHERE id = emp_id;
    END IF;
    
    RETURN FALSE;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ===========================
-- وظائف المصادقة
-- ===========================

CREATE OR REPLACE FUNCTION authenticate_employee(
    employee_phone TEXT,
    employee_password TEXT
) RETURNS JSON AS $$
DECLARE
    emp_record RECORD;
    center_record RECORD;
    is_locked BOOLEAN;
    login_time TIMESTAMPTZ;
BEGIN
    login_time := NOW();

    IF employee_phone IS NULL OR TRIM(employee_phone) = '' THEN
        RETURN json_build_object('success', false, 'error', 'رقم الهاتف مطلوب');
    END IF;

    IF employee_password IS NULL OR employee_password = '' THEN
        RETURN json_build_object('success', false, 'error', 'كلمة المرور مطلوبة');
    END IF;

    SELECT * INTO emp_record
    FROM employees 
    WHERE phone = TRIM(employee_phone) AND is_active = true;

    IF NOT FOUND THEN
        RETURN json_build_object('success', false, 'error', 'رقم الهاتف غير مسجل أو الحساب معطل');
    END IF;

    SELECT is_account_locked(emp_record.id) INTO is_locked;
    IF is_locked THEN
        RETURN json_build_object('success', false, 'error', 'الحساب مقفل مؤقتاً. حاول مرة أخرى خلال 15 دقيقة.');
    END IF;

    IF emp_record.password_hash IS NULL OR emp_record.password_hash = '' THEN
        RETURN json_build_object('success', false, 'error', 'يجب تحديث كلمة المرور من الإدارة أولاً');
    END IF;

    IF NOT verify_password(employee_password, emp_record.password_hash) THEN
        UPDATE employees 
        SET 
            failed_login_attempts = COALESCE(failed_login_attempts, 0) + 1,
            locked_until = CASE 
                WHEN COALESCE(failed_login_attempts, 0) + 1 >= 5 
                THEN login_time + INTERVAL '15 minutes'
                ELSE NULL
            END,
            updated_at = login_time
        WHERE id = emp_record.id;

        IF COALESCE(emp_record.failed_login_attempts, 0) + 1 >= 5 THEN
            RETURN json_build_object('success', false, 'error', 'تم قفل الحساب لمدة 15 دقيقة بسبب المحاولات المتكررة');
        ELSE
            RETURN json_build_object('success', false, 'error', 'كلمة المرور غير صحيحة. المحاولات المتبقية: ' || (4 - COALESCE(emp_record.failed_login_attempts, 0)));
        END IF;
    END IF;

    SELECT * INTO center_record
    FROM centers
    WHERE id = emp_record.center_id;

    UPDATE employees 
    SET 
        failed_login_attempts = 0, 
        locked_until = NULL, 
        last_login = login_time,
        updated_at = login_time
    WHERE id = emp_record.id;

    RETURN json_build_object(
        'success', true,
        'login_time', login_time,
        'employee', json_build_object(
            'id', emp_record.id,
            'name', emp_record.name,
            'phone', emp_record.phone,
            'position', emp_record.position,
            'center_id', emp_record.center_id,
            'status', emp_record.status,
            'last_login', login_time,
            'center', CASE 
                WHEN center_record.id IS NOT NULL THEN
                    json_build_object(
                        'id', center_record.id,
                        'name', center_record.name,
                        'latitude', center_record.latitude,
                        'longitude', center_record.longitude,
                        'radius', center_record.radius
                    )
                ELSE NULL
            END
        )
    );
    
EXCEPTION
    WHEN OTHERS THEN
        RETURN json_build_object('success', false, 'error', 'خطأ في النظام: ' || SQLERRM);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION authenticate_user(
    user_username TEXT,
    user_password TEXT
) RETURNS JSON AS $$
DECLARE
    user_record RECORD;
    user_centers INTEGER[];
    login_time TIMESTAMPTZ;
BEGIN
    login_time := NOW();
    
    IF user_username IS NULL OR TRIM(user_username) = '' THEN
        RETURN json_build_object('success', false, 'error', 'اسم المستخدم مطلوب');
    END IF;
    
    IF user_password IS NULL OR user_password = '' THEN
        RETURN json_build_object('success', false, 'error', 'كلمة المرور مطلوبة');
    END IF;
    
    SELECT * INTO user_record
    FROM users 
    WHERE username = TRIM(user_username) AND is_active = true;
    
    IF NOT FOUND THEN
        RETURN json_build_object('success', false, 'error', 'اسم المستخدم غير موجود أو الحساب معطل');
    END IF;
    
    IF user_record.locked_until IS NOT NULL AND user_record.locked_until > login_time THEN
        RETURN json_build_object('success', false, 'error', 'الحساب مقفل مؤقتاً. حاول مرة أخرى لاحقاً.');
    END IF;
    
    IF NOT (user_record.password_hash = crypt(user_password, user_record.password_hash)) THEN
        UPDATE users 
        SET 
            failed_login_attempts = COALESCE(failed_login_attempts, 0) + 1,
            locked_until = CASE 
                WHEN COALESCE(failed_login_attempts, 0) + 1 >= 5 
                THEN login_time + INTERVAL '15 minutes'
                ELSE NULL
            END,
            updated_at = login_time
        WHERE id = user_record.id;
        
        RETURN json_build_object('success', false, 'error', 'كلمة المرور غير صحيحة');
    END IF;
    
    IF user_record.role = 'admin' THEN
        user_centers := ARRAY(SELECT id FROM centers);
    ELSE
        SELECT ARRAY_AGG(center_id) INTO user_centers
        FROM user_center_permissions 
        WHERE user_id = user_record.id AND can_view = true;
    END IF;
    
    UPDATE users 
    SET 
        failed_login_attempts = 0, 
        locked_until = NULL, 
        last_login = login_time,
        updated_at = login_time
    WHERE id = user_record.id;
    
    RETURN json_build_object(
        'success', true,
        'login_time', login_time,
        'user', json_build_object(
            'id', user_record.id,
            'username', user_record.username,
            'full_name', user_record.full_name,
            'email', user_record.email,
            'phone', user_record.phone,
            'role', user_record.role,
            'last_login', login_time,
            'permissions', json_build_object(
                'can_add_centers', user_record.can_add_centers,
                'can_add_employees', user_record.can_add_employees,
                'can_edit_centers', user_record.can_edit_centers,
                'can_edit_employees', user_record.can_edit_employees,
                'can_delete_centers', user_record.can_delete_centers,
                'can_delete_employees', user_record.can_delete_employees,
                'can_view_all_centers', user_record.can_view_all_centers,
                'can_view_all_employees', user_record.can_view_all_employees
            ),
            'allowed_centers', COALESCE(user_centers, ARRAY[]::INTEGER[])
        )
    );
    
EXCEPTION
    WHEN OTHERS THEN
        RETURN json_build_object('success', false, 'error', 'خطأ في النظام: ' || SQLERRM);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ===========================
-- وظائف الإدارة - إضافة
-- ===========================

CREATE OR REPLACE FUNCTION add_employee(
    employee_name TEXT,
    employee_phone TEXT,
    employee_password TEXT,
    employee_position TEXT DEFAULT 'موظف',
    employee_center_id INTEGER DEFAULT NULL,
    admin_user_id INTEGER DEFAULT NULL
) RETURNS JSON AS $$
DECLARE
    new_employee_id INTEGER;
    center_exists BOOLEAN;
    creation_time TIMESTAMPTZ;
BEGIN
    creation_time := NOW();
    
    IF employee_name IS NULL OR TRIM(employee_name) = '' THEN
        RETURN json_build_object('success', false, 'error', 'اسم الموظف مطلوب');
    END IF;
    
    IF employee_phone IS NULL OR TRIM(employee_phone) = '' THEN
        RETURN json_build_object('success', false, 'error', 'رقم الهاتف مطلوب');
    END IF;
    
    IF NOT employee_phone ~ '^(077|078|076|075|079)[0-9]{8}$' THEN
        RETURN json_build_object('success', false, 'error', 'رقم الهاتف يجب أن يكون 11 رقم ويبدأ بـ 077 أو 078 أو 076 أو 075 أو 079');
    END IF;
    
    IF EXISTS (SELECT 1 FROM employees WHERE phone = TRIM(employee_phone)) THEN
        RETURN json_build_object('success', false, 'error', 'رقم الهاتف مستخدم مسبقاً');
    END IF;
    
    IF employee_center_id IS NOT NULL THEN
        SELECT EXISTS(SELECT 1 FROM centers WHERE id = employee_center_id) INTO center_exists;
        IF NOT center_exists THEN
            RETURN json_build_object('success', false, 'error', 'المركز المحدد غير موجود');
        END IF;
    END IF;
    
    INSERT INTO employees (
        name, phone, password_hash, position, center_id, 
        status, is_active, password_changed_at, created_at, updated_at
    )
    VALUES (
        TRIM(employee_name), 
        TRIM(employee_phone), 
        hash_password(employee_password), 
        COALESCE(TRIM(employee_position), 'موظف'), 
        employee_center_id,
        'inactive', 
        true,
        creation_time, 
        creation_time, 
        creation_time
    )
    RETURNING id INTO new_employee_id;
    
    -- تسجيل العملية في main_logs
    INSERT INTO main_logs (action, entity_type, entity_name, latitude, longitude, user_id, occurred_at)
    VALUES ('add', 'employee', employee_name, NULL, NULL, admin_user_id, creation_time);
    
    RETURN json_build_object(
        'success', true, 
        'employee_id', new_employee_id, 
        'message', 'تم إضافة الموظف بنجاح',
        'created_at', creation_time
    );
    
EXCEPTION
    WHEN OTHERS THEN
        RETURN json_build_object('success', false, 'error', 'خطأ في النظام: ' || SQLERRM);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- حذف جميع الدوال المتعارضة باسم add_user قبل إعادة تعريف الدالة الصحيحة
DROP FUNCTION IF EXISTS add_user(user_username text, user_password text, user_full_name text, user_email text, user_phone text, user_role text, center_ids integer[]);
DROP FUNCTION IF EXISTS add_user(user_username text, user_password text, user_full_name text, user_email text, user_phone text, user_role text, center_ids integer[], admin_user_id integer);
DROP FUNCTION IF EXISTS add_user(user_username text, user_password text, user_full_name text, user_email text, user_phone text, user_role text, center_ids integer[], admin_user_id uuid);

CREATE OR REPLACE FUNCTION add_user(
    user_username TEXT,
    user_password TEXT,
    user_full_name TEXT,
    user_email TEXT DEFAULT NULL,
    user_phone TEXT DEFAULT NULL,
    user_role TEXT DEFAULT 'user',
    center_ids INTEGER[] DEFAULT NULL,
    admin_user_id INTEGER DEFAULT NULL
) RETURNS JSON AS $$
DECLARE
    new_user_id INTEGER;
    center_id INTEGER;
    creation_time TIMESTAMPTZ;
BEGIN
    creation_time := NOW();
    
    IF user_username IS NULL OR TRIM(user_username) = '' THEN
        RETURN json_build_object('success', false, 'error', 'اسم المستخدم مطلوب');
    END IF;
    
    IF user_full_name IS NULL OR TRIM(user_full_name) = '' THEN
        RETURN json_build_object('success', false, 'error', 'الاسم الكامل مطلوب');
    END IF;
    
    IF user_password IS NULL OR LENGTH(user_password) < 6 THEN
        RETURN json_build_object('success', false, 'error', 'كلمة المرور يجب أن تكون 6 أحرف على الأقل');
    END IF;
    
    IF EXISTS (SELECT 1 FROM users WHERE username = TRIM(user_username)) THEN
        RETURN json_build_object('success', false, 'error', 'اسم المستخدم مستخدم مسبقاً');
    END IF;
    
    INSERT INTO users (
        username, password_hash, full_name, email, phone, role,
        can_delete_centers, can_delete_employees, 
        can_view_all_centers, can_view_all_employees,
        is_active, is_hidden,
        created_at, updated_at, password_changed_at
    )
    VALUES (
        TRIM(user_username), 
        hash_password(user_password), 
        TRIM(user_full_name), 
        TRIM(user_email), 
        TRIM(user_phone), 
        COALESCE(user_role, 'user'),
        CASE WHEN user_role = 'admin' THEN true ELSE false END,
        CASE WHEN user_role = 'admin' THEN true ELSE false END,
        CASE WHEN user_role = 'admin' THEN true ELSE false END,
        CASE WHEN user_role = 'admin' THEN true ELSE false END,
        true, false, -- المستخدمين الجدد غير مخفيين
        creation_time,
        creation_time,
        creation_time
    )
    RETURNING id INTO new_user_id;
    
    IF user_role != 'admin' AND center_ids IS NOT NULL THEN
        -- تعديل: تغيير اسم متغير الحلقة لتفادي الغموض مع اسم العمود
        FOREACH center_id IN ARRAY center_ids
        LOOP
            INSERT INTO user_center_permissions (user_id, center_id, can_view, can_manage, created_at)
            VALUES (new_user_id, center_id, true, true, creation_time)
            ON CONFLICT (user_id, center_id) DO NOTHING;
        END LOOP;
    END IF;
    
    -- تسجيل العملية في main_logs
    INSERT INTO main_logs (action, entity_type, entity_name, latitude, longitude, user_id, occurred_at)
    VALUES ('add', 'user', user_full_name, NULL, NULL, admin_user_id, creation_time);
    
    RETURN json_build_object(
        'success', true, 
        'user_id', new_user_id, 
        'message', 'تم إضافة المستخدم بنجاح',
        'created_at', creation_time
    );
    
EXCEPTION
    WHEN OTHERS THEN
        RETURN json_build_object('success', false, 'error', 'خطأ في النظام: ' || SQLERRM);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION add_center(
    center_name TEXT,
    center_longitude DECIMAL,
    center_latitude DECIMAL,
    center_radius INTEGER DEFAULT 100,
    admin_user_id INTEGER DEFAULT NULL
) RETURNS JSON AS $$
DECLARE
    new_center_id INTEGER;
    creation_time TIMESTAMPTZ;
BEGIN
    creation_time := NOW();
    
    IF center_name IS NULL OR TRIM(center_name) = '' THEN
        RETURN json_build_object('success', false, 'error', 'اسم المركز مطلوب');
    END IF;
    
    IF center_longitude IS NULL OR center_latitude IS NULL THEN
        RETURN json_build_object('success', false, 'error', 'موقع المركز مطلوب');
    END IF;
    
    IF center_radius < 50 OR center_radius > 1000 THEN
        RETURN json_build_object('success', false, 'error', 'نطاق المركز يجب أن يكون بين 50 و 1000 متر');
    END IF;
    
    INSERT INTO centers (name, longitude, latitude, radius, created_at, updated_at)
    VALUES (TRIM(center_name), center_longitude, center_latitude, center_radius, creation_time, creation_time)
    RETURNING id INTO new_center_id;
    
    -- تسجيل العملية في main_logs
    INSERT INTO main_logs (action, entity_type, entity_name, latitude, longitude, user_id, occurred_at)
    VALUES ('add', 'center', center_name, center_longitude, center_latitude, admin_user_id, creation_time);
    
    RETURN json_build_object(
        'success', true, 
        'center_id', new_center_id, 
        'message', 'تم إضافة المركز بنجاح',
        'created_at', creation_time
    );
    
EXCEPTION
    WHEN OTHERS THEN
        RETURN json_build_object('success', false, 'error', 'خطأ في النظام: ' || SQLERRM);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ===========================
-- وظائف الإدارة - تعديل
-- ===========================

CREATE OR REPLACE FUNCTION update_employee(
    employee_id INTEGER,
    employee_name TEXT DEFAULT NULL,
    employee_phone TEXT DEFAULT NULL,
    employee_position TEXT DEFAULT NULL,
    employee_center_id INTEGER DEFAULT NULL,
    employee_status VARCHAR(20) DEFAULT NULL,
    employee_notes TEXT DEFAULT NULL,
    admin_user_id INTEGER DEFAULT NULL,
    old_name TEXT DEFAULT NULL
) RETURNS JSON AS $$
DECLARE
    update_time TIMESTAMPTZ;
    phone_exists BOOLEAN;
    center_exists BOOLEAN;
BEGIN
    update_time := NOW();
    -- التحقق من وجود الموظف
    IF NOT EXISTS (SELECT 1 FROM employees WHERE id = employee_id AND is_active = true) THEN
        RETURN json_build_object('success', false, 'error', 'الموظف غير موجود');
    END IF;
    -- التحقق من رقم الهاتف إذا تم تغييره
    IF employee_phone IS NOT NULL AND TRIM(employee_phone) != '' THEN
        SELECT EXISTS(
            SELECT 1 FROM employees 
            WHERE phone = TRIM(employee_phone) AND id != employee_id
        ) INTO phone_exists;
        IF phone_exists THEN
            RETURN json_build_object('success', false, 'error', 'رقم الهاتف مستخدم من موظف آخر');
        END IF;
        IF NOT employee_phone ~ '^(077|078|076|075|079)[0-9]{8}$' THEN
            RETURN json_build_object('success', false, 'error', 'رقم الهاتف يجب أن يكون 11 رقم ويبدأ بـ 077 أو 078 أو 076 أو 075 أو 079');
        END IF;
    END IF;
    -- التحقق من وجود المركز
    IF employee_center_id IS NOT NULL THEN
        SELECT EXISTS(SELECT 1 FROM centers WHERE id = employee_center_id) INTO center_exists;
        IF NOT center_exists THEN
            RETURN json_build_object('success', false, 'error', 'المركز المحدد غير موجود');
        END IF;
    END IF;
    -- تحديث البيانات
    UPDATE employees 
    SET 
        name = COALESCE(TRIM(employee_name), name),
        phone = COALESCE(TRIM(employee_phone), phone),
        position = COALESCE(TRIM(employee_position), position),
        center_id = COALESCE(employee_center_id, center_id),
        status = COALESCE(employee_status, status),
        notes = COALESCE(employee_notes, notes),
        updated_at = update_time
    WHERE id = employee_id;
    -- تسجيل العملية في main_logs
    INSERT INTO main_logs (action, entity_type, entity_name, old_name, latitude, longitude, user_id, occurred_at)
    VALUES ('update', 'employee', employee_name, old_name, NULL, NULL, admin_user_id, update_time);
    RETURN json_build_object(
        'success', true, 
        'message', 'تم تحديث بيانات الموظف بنجاح',
        'updated_at', update_time
    );
EXCEPTION
    WHEN OTHERS THEN
        RETURN json_build_object('success', false, 'error', 'خطأ في النظام: ' || SQLERRM);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION update_user(
    user_id INTEGER,
    user_username TEXT DEFAULT NULL,
    user_full_name TEXT DEFAULT NULL,
    user_email TEXT DEFAULT NULL,
    user_phone TEXT DEFAULT NULL,
    user_role TEXT DEFAULT NULL,
    center_ids INTEGER[] DEFAULT NULL,
    admin_user_id INTEGER DEFAULT NULL,
    old_name TEXT DEFAULT NULL
) RETURNS JSON AS $$
DECLARE
    update_time TIMESTAMPTZ;
    username_exists BOOLEAN;
    center_id INTEGER;
BEGIN
    update_time := NOW();
    IF NOT EXISTS (SELECT 1 FROM users WHERE id = update_user.user_id AND is_active = true) THEN
        RETURN json_build_object('success', false, 'error', 'المستخدم غير موجود');
    END IF;
    IF user_username IS NOT NULL AND TRIM(user_username) != '' THEN
        SELECT EXISTS(
            SELECT 1 FROM users 
            WHERE username = TRIM(user_username) AND id != update_user.user_id
        ) INTO username_exists;
        IF username_exists THEN
            RETURN json_build_object('success', false, 'error', 'اسم المستخدم مستخدم من مستخدم آخر');
        END IF;
    END IF;
    UPDATE users 
    SET 
        username = COALESCE(TRIM(user_username), username),
        full_name = COALESCE(TRIM(user_full_name), full_name),
        email = COALESCE(TRIM(user_email), email),
        phone = COALESCE(TRIM(user_phone), phone),
        role = COALESCE(user_role, role),
        can_delete_centers = CASE WHEN user_role = 'admin' THEN true ELSE can_delete_centers END,
        can_delete_employees = CASE WHEN user_role = 'admin' THEN true ELSE can_delete_employees END,
        can_view_all_centers = CASE WHEN user_role = 'admin' THEN true ELSE can_view_all_centers END,
        can_view_all_employees = CASE WHEN user_role = 'admin' THEN true ELSE can_view_all_employees END,
        updated_at = update_time
    WHERE id = update_user.user_id;
    IF user_role != 'admin' AND center_ids IS NOT NULL THEN
        DELETE FROM user_center_permissions WHERE user_id = update_user.user_id;
        FOREACH center_id IN ARRAY center_ids
        LOOP
            INSERT INTO user_center_permissions (user_id, center_id, can_view, can_manage, created_at)
            VALUES (update_user.user_id, center_id, true, true, update_time)
            ON CONFLICT (user_id, center_id) DO NOTHING;
        END LOOP;
    ELSIF user_role = 'admin' THEN
        DELETE FROM user_center_permissions WHERE user_id = update_user.user_id;
    END IF;
    -- تسجيل العملية في main_logs
    INSERT INTO main_logs (action, entity_type, entity_name, old_name, latitude, longitude, user_id, occurred_at)
    VALUES ('update', 'user', user_full_name, old_name, NULL, NULL, admin_user_id, update_time);
    RETURN json_build_object(
        'success', true, 
        'message', 'تم تحديث بيانات المستخدم بنجاح',
        'updated_at', update_time
    );
EXCEPTION
    WHEN OTHERS THEN
        RETURN json_build_object('success', false, 'error', 'خطأ في النظام: ' || SQLERRM);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION update_center(
    center_id INTEGER,
    center_name TEXT DEFAULT NULL,
    center_longitude DECIMAL DEFAULT NULL,
    center_latitude DECIMAL DEFAULT NULL,
    center_radius INTEGER DEFAULT NULL,
    admin_user_id INTEGER DEFAULT NULL,
    old_name TEXT DEFAULT NULL
) RETURNS JSON AS $$
DECLARE
    update_time TIMESTAMPTZ;
BEGIN
    update_time := NOW();
    -- التحقق من وجود المركز
    IF NOT EXISTS (SELECT 1 FROM centers WHERE id = center_id) THEN
        RETURN json_build_object('success', false, 'error', 'المركز غير موجود');
    END IF;
    -- التحقق من صحة النطاق
    IF center_radius IS NOT NULL AND (center_radius < 50 OR center_radius > 1000) THEN
        RETURN json_build_object('success', false, 'error', 'نطاق المركز يجب أن يكون بين 50 و 1000 متر');
    END IF;
    -- تحديث البيانات
    UPDATE centers 
    SET 
        name = COALESCE(TRIM(center_name), name),
        longitude = COALESCE(center_longitude, longitude),
        latitude = COALESCE(center_latitude, latitude),
        radius = COALESCE(center_radius, radius),
        updated_at = update_time
    WHERE id = center_id;
    -- تسجيل العملية في main_logs
    INSERT INTO main_logs (action, entity_type, entity_name, old_name, latitude, longitude, user_id, occurred_at)
    VALUES ('update', 'center', center_name, old_name, center_longitude, center_latitude, admin_user_id, update_time);
    RETURN json_build_object(
        'success', true, 
        'message', 'تم تحديث بيانات المركز بنجاح',
        'updated_at', update_time
    );
EXCEPTION
    WHEN OTHERS THEN
        RETURN json_build_object('success', false, 'error', 'خطأ في النظام: ' || SQLERRM);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ===========================
-- وظائف الإدارة - حذف
-- ===========================

CREATE OR REPLACE FUNCTION delete_employee(employee_id INTEGER, admin_user_id INTEGER DEFAULT NULL) 
RETURNS JSON AS $$
DECLARE
    delete_time TIMESTAMPTZ;
    emp_name TEXT;
BEGIN
    delete_time := NOW();
    
    -- التحقق من وجود الموظف
    SELECT name INTO emp_name FROM employees WHERE id = employee_id AND is_active = true;
    
    IF NOT FOUND THEN
        RETURN json_build_object('success', false, 'error', 'الموظف غير موجود');
    END IF;
    
    -- حذف منطقي - تعطيل الحساب
    UPDATE employees 
    SET 
        is_active = false,
        status = 'inactive',
        updated_at = delete_time
    WHERE id = employee_id;
    
    -- إضافة سجل بالحذف
    INSERT INTO logs (employee_id, action, notes, occurred_at, created_at)
    VALUES (employee_id, 'account_deactivated', 'تم تعطيل الحساب من قبل الإدارة', delete_time, delete_time);
    
    -- تسجيل العملية في main_logs
    INSERT INTO main_logs (action, entity_type, entity_name, latitude, longitude, user_id, occurred_at)
    VALUES ('delete', 'employee', emp_name, NULL, NULL, admin_user_id, delete_time);
    
    RETURN json_build_object(
        'success', true, 
        'message', 'تم حذف الموظف "' || emp_name || '" بنجاح',
        'deleted_at', delete_time
    );
    
EXCEPTION
    WHEN OTHERS THEN
        RETURN json_build_object('success', false, 'error', 'خطأ في النظام: ' || SQLERRM);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION delete_user(user_id INTEGER, admin_user_id INTEGER DEFAULT NULL) 
RETURNS JSON AS $$
DECLARE
    delete_time TIMESTAMPTZ;
    user_name TEXT;
    user_role_val TEXT;
BEGIN
    delete_time := NOW();
    
    -- التحقق من وجود المستخدم
    SELECT full_name, role INTO user_name, user_role_val 
    FROM users WHERE id = delete_user.user_id AND is_active = true;
    
    IF NOT FOUND THEN
        RETURN json_build_object('success', false, 'error', 'المستخدم غير موجود');
    END IF;
    
    -- منع حذف المدير الأخير
    IF user_role_val = 'admin' AND (SELECT COUNT(*) FROM users WHERE role = 'admin' AND is_active = true) <= 1 THEN
        RETURN json_build_object('success', false, 'error', 'لا يمكن حذف المدير الأخير في النظام');
    END IF;
    
    -- حذف منطقي - تعطيل الحساب
    UPDATE users 
    SET 
        is_active = false,
        updated_at = delete_time
    WHERE id = delete_user.user_id;
    
    -- حذف صلاحيات المراكز
    DELETE FROM user_center_permissions WHERE user_id = delete_user.user_id;
    
    -- تسجيل العملية في main_logs
    INSERT INTO main_logs (action, entity_type, entity_name, latitude, longitude, user_id, occurred_at)
    VALUES ('delete', 'user', user_name, NULL, NULL, admin_user_id, delete_time);
    
    RETURN json_build_object(
        'success', true, 
        'message', 'تم حذف المستخدم "' || user_name || '" بنجاح',
        'deleted_at', delete_time
    );
    
EXCEPTION
    WHEN OTHERS THEN
        RETURN json_build_object('success', false, 'error', 'خطأ في النظام: ' || SQLERRM);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION delete_center(center_id INTEGER, admin_user_id INTEGER DEFAULT NULL) 
RETURNS JSON AS $$
DECLARE
    delete_time TIMESTAMPTZ;
    center_name_val TEXT;
    employees_count INTEGER;
BEGIN
    delete_time := NOW();
    
    -- التحقق من وجود المركز
    SELECT name INTO center_name_val FROM centers WHERE id = center_id;
    
    IF NOT FOUND THEN
        RETURN json_build_object('success', false, 'error', 'المركز غير موجود');
    END IF;
    
    -- التحقق من وجود موظفين مرتبطين
    SELECT COUNT(*) INTO employees_count 
    FROM employees WHERE center_id = center_id AND is_active = true;
    
    IF employees_count > 0 THEN
        RETURN json_build_object('success', false, 'error', 'لا يمكن حذف المركز لوجود ' || employees_count || ' موظف مرتبط به');
    END IF;
    
    -- حذف المركز
    DELETE FROM centers WHERE id = center_id;
    
    -- تسجيل العملية في main_logs
    INSERT INTO main_logs (action, entity_type, entity_name, latitude, longitude, user_id, occurred_at)
    VALUES ('delete', 'center', center_name_val, NULL, NULL, admin_user_id, delete_time);
    
    RETURN json_build_object(
        'success', true, 
        'message', 'تم حذف المركز "' || center_name_val || '" بنجاح',
        'deleted_at', delete_time
    );
    
EXCEPTION
    WHEN OTHERS THEN
        RETURN json_build_object('success', false, 'error', 'خطأ في النظام: ' || SQLERRM);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ===========================
-- وظائف الموقع والتتبع
-- ===========================

CREATE OR REPLACE FUNCTION calculate_distance_meters(
    lat1 DECIMAL, lng1 DECIMAL, 
    lat2 DECIMAL, lng2 DECIMAL
) RETURNS DECIMAL AS $$
DECLARE
    earth_radius DECIMAL := 6371000;
    dlat DECIMAL;
    dlng DECIMAL;
    a DECIMAL;
    c DECIMAL;
BEGIN
    dlat := radians(lat2 - lat1);
    dlng := radians(lng2 - lng1);
    
    a := sin(dlat/2) * sin(dlat/2) + 
         cos(radians(lat1)) * cos(radians(lat2)) * 
         sin(dlng/2) * sin(dlng/2);
    
    c := 2 * atan2(sqrt(a), sqrt(1-a));
    
    RETURN earth_radius * c;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION check_employee_distance(
    employee_id INTEGER,
    current_lat DECIMAL,
    current_lng DECIMAL,
    current_accuracy DECIMAL DEFAULT NULL
) RETURNS JSON AS $$
DECLARE
    emp_record RECORD;
    distance_meters DECIMAL;
    is_in_range BOOLEAN;
    current_status VARCHAR(20);
    action_taken VARCHAR(50);
    check_time TIMESTAMPTZ;
BEGIN
    check_time := NOW();
    
    SELECT 
        e.*, 
        c.latitude as center_lat, 
        c.longitude as center_lng, 
        c.radius,
        c.name as center_name
    INTO emp_record
    FROM employees e
    JOIN centers c ON e.center_id = c.id
    WHERE e.id = employee_id AND e.is_active = true;
    
    IF NOT FOUND THEN
        RETURN json_build_object('success', false, 'error', 'بيانات الموظف أو المركز غير موجودة');
    END IF;
    
    distance_meters := calculate_distance_meters(
        current_lat, current_lng, 
        emp_record.center_lat, emp_record.center_lng
    );
    
    is_in_range := distance_meters <= (emp_record.radius + 50);
    current_status := emp_record.status;
    action_taken := 'location_update';
    
    UPDATE employees 
    SET 
        last_location_update = check_time,
        updated_at = check_time
    WHERE id = employee_id;
    
    IF is_in_range AND emp_record.status = 'inactive' THEN
        UPDATE employees SET 
            status = 'active', 
            updated_at = check_time 
        WHERE id = employee_id;
        
        INSERT INTO logs (employee_id, center_id, action, latitude, longitude, accuracy, occurred_at, created_at)
        VALUES (employee_id, emp_record.center_id, 'auto_checkin', current_lat, current_lng, current_accuracy, check_time, check_time);
        
        -- تحديث العداد الإجمالي
        UPDATE attendance_total SET total = total + 1, updated_at = check_time;
        
        current_status := 'active';
        action_taken := 'auto_checkin';
        
    ELSIF NOT is_in_range AND emp_record.status = 'active' THEN
        UPDATE employees SET 
            status = 'inactive', 
            auto_checkout_time = check_time, 
            updated_at = check_time 
        WHERE id = employee_id;
        
        INSERT INTO logs (employee_id, center_id, action, latitude, longitude, accuracy, occurred_at, created_at)
        VALUES (employee_id, emp_record.center_id, 'auto_checkout', current_lat, current_lng, current_accuracy, check_time, check_time);
        
        current_status := 'inactive';
        action_taken := 'auto_checkout';
        
    ELSE
        INSERT INTO logs (employee_id, center_id, action, latitude, longitude, accuracy, occurred_at, created_at)
        VALUES (employee_id, emp_record.center_id, 
                CASE WHEN is_in_range THEN 'location_update' ELSE 'out_of_range' END,
                current_lat, current_lng, current_accuracy, check_time, check_time);
        
        IF NOT is_in_range THEN
            action_taken := 'out_of_range';
        END IF;
    END IF;
    
    RETURN json_build_object(
        'success', true,
        'distance', ROUND(distance_meters, 1),
        'in_range', is_in_range,
        'status', current_status,
        'action', action_taken,
        'center_name', emp_record.center_name,
        'radius', emp_record.radius,
        'timestamp', check_time,
        'formatted_time', format_iraq_time(check_time)
    );
    
EXCEPTION
    WHEN OTHERS THEN
        RETURN json_build_object('success', false, 'error', 'خطأ في معالجة الموقع: ' || SQLERRM);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ===========================
-- وظائف التقارير (تصحيح center_id)
-- ===========================

CREATE OR REPLACE FUNCTION get_user_allowed_centers(input_user_id INTEGER)
RETURNS TABLE(
    center_id INTEGER,
    center_name VARCHAR(255),
    longitude DECIMAL(11, 8),
    latitude DECIMAL(11, 8),
    radius INTEGER,
    can_manage BOOLEAN,
    created_at_formatted TEXT,
    updated_at_formatted TEXT
) AS $$
DECLARE
    user_role VARCHAR(20);
BEGIN
    SELECT role INTO user_role FROM users WHERE id = input_user_id AND is_active = true;
    
    IF NOT FOUND THEN
        RETURN;
    END IF;
    
    IF user_role = 'admin' THEN
        RETURN QUERY
        SELECT 
            c.id AS center_id, 
            c.name, 
            c.longitude, 
            c.latitude, 
            c.radius, 
            TRUE as can_manage,
            format_iraq_time(c.created_at),
            format_iraq_time(c.updated_at)
        FROM centers c
        ORDER BY c.name;
    ELSE
        RETURN QUERY
        SELECT 
            c.id AS center_id, 
            c.name, 
            c.longitude, 
            c.latitude, 
            c.radius, 
            ucp.can_manage,
            format_iraq_time(c.created_at),
            format_iraq_time(c.updated_at)
        FROM centers c
        JOIN user_center_permissions ucp ON c.id = ucp.center_id
        WHERE ucp.user_id = input_user_id AND ucp.can_view = true
        ORDER BY c.name;
    END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_user_allowed_employees(input_user_id INTEGER)
RETURNS TABLE(
    employee_id INTEGER,
    employee_name VARCHAR(255),
    phone VARCHAR(20),
    job_position VARCHAR(255),
    status VARCHAR(20),
    center_id INTEGER,
    center_name VARCHAR(255),
    last_login_formatted TEXT,
    last_location_formatted TEXT,
    created_at_formatted TEXT
) AS $$
DECLARE
    user_role VARCHAR(20);
    allowed_center_ids INTEGER[];
BEGIN
    SELECT role INTO user_role FROM users WHERE id = input_user_id AND is_active = true;
    
    IF NOT FOUND THEN
        RETURN;
    END IF;
    
    IF user_role = 'admin' THEN
        RETURN QUERY
        SELECT 
            e.id AS employee_id, 
            e.name AS employee_name, 
            e.phone, 
            e.position, 
            e.status, 
            e.center_id, 
            c.name AS center_name,
            format_iraq_time(e.last_login),
            format_iraq_time(e.last_location_update),
            format_iraq_time(e.created_at)
        FROM employees e
        LEFT JOIN centers c ON e.center_id = c.id
        WHERE e.is_active = true
        ORDER BY e.name;
    ELSE
        SELECT ARRAY_AGG(ucp.center_id) INTO allowed_center_ids
        FROM user_center_permissions ucp
        WHERE ucp.user_id = input_user_id 
        AND ucp.can_view = true;
        
        RETURN QUERY
        SELECT 
            e.id AS employee_id, 
            e.name AS employee_name, 
            e.phone, 
            e.position, 
            e.status, 
            e.center_id, 
            c.name AS center_name,
            format_iraq_time(e.last_login),
            format_iraq_time(e.last_location_update),
            format_iraq_time(e.created_at)
        FROM employees e
        LEFT JOIN centers c ON e.center_id = c.id
        WHERE e.is_active = true 
        AND e.center_id = ANY(COALESCE(allowed_center_ids, ARRAY[]::INTEGER[]))
        ORDER BY e.name;
    END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ===========================
-- وظائف الأوامر البعيدة
-- ===========================

CREATE OR REPLACE FUNCTION add_remote_command(
    employee_id INTEGER,
    command_text TEXT,
    admin_user_id INTEGER DEFAULT NULL
) RETURNS JSON AS $$
DECLARE
    new_command_id INTEGER;
    creation_time TIMESTAMPTZ;
BEGIN
    creation_time := NOW();
    
    IF NOT EXISTS (SELECT 1 FROM employees WHERE id = employee_id AND is_active = true) THEN
        RETURN json_build_object('success', false, 'error', 'الموظف غير موجود');
    END IF;
    
    IF command_text IS NULL OR TRIM(command_text) = '' THEN
        RETURN json_build_object('success', false, 'error', 'الأمر مطلوب');
    END IF;
    
    INSERT INTO remote_commands (employee_id, command, created_at)
    VALUES (employee_id, TRIM(command_text), creation_time)
    RETURNING id INTO new_command_id;
    
    -- تسجيل العملية في main_logs
    INSERT INTO main_logs (action, entity_type, entity_name, latitude, longitude, user_id, occurred_at)
    VALUES ('add', 'command', command_text, NULL, NULL, admin_user_id, creation_time);
    
    RETURN json_build_object(
        'success', true,
        'command_id', new_command_id,
        'message', 'تم إضافة الأمر بنجاح',
        'created_at', creation_time
    );
    
EXCEPTION
    WHEN OTHERS THEN
        RETURN json_build_object('success', false, 'error', 'خطأ في النظام: ' || SQLERRM);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_employee_commands(employee_id INTEGER)
RETURNS TABLE(
    command_id INTEGER,
    command_text TEXT,
    executed BOOLEAN,
    created_at_formatted TEXT,
    executed_at_formatted TEXT
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        rc.id,
        rc.command,
        rc.executed,
        format_iraq_time(rc.created_at),
        format_iraq_time(rc.executed_at)
    FROM remote_commands rc
    WHERE rc.employee_id = employee_id
    AND rc.executed = false
    ORDER BY rc.created_at DESC;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION execute_command(command_id INTEGER, admin_user_id INTEGER DEFAULT NULL)
RETURNS JSON AS $$
DECLARE
    execution_time TIMESTAMPTZ;
BEGIN
    execution_time := NOW();
    
    IF NOT EXISTS (SELECT 1 FROM remote_commands WHERE id = command_id) THEN
        RETURN json_build_object('success', false, 'error', 'الأمر غير موجود');
    END IF;
    
    UPDATE remote_commands 
    SET 
        executed = true,
        executed_at = execution_time
    WHERE id = command_id;
    
    -- تسجيل العملية في main_logs
    INSERT INTO main_logs (action, entity_type, entity_name, latitude, longitude, user_id, occurred_at)
    VALUES ('execute', 'command', NULL, NULL, NULL, admin_user_id, execution_time);
    
    RETURN json_build_object(
        'success', true,
        'message', 'تم تنفيذ الأمر بنجاح',
        'executed_at', execution_time
    );
    
EXCEPTION
    WHEN OTHERS THEN
        RETURN json_build_object('success', false, 'error', 'خطأ في النظام: ' || SQLERRM);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ===========================
-- وظائف إضافية
-- ===========================

CREATE OR REPLACE FUNCTION auto_cleanup_employees()
RETURNS JSON AS $$
DECLARE
    checkout_count INTEGER := 0;
    emp_record RECORD;
    cleanup_time TIMESTAMPTZ;
BEGIN
    cleanup_time := NOW();
    
    FOR emp_record IN 
        SELECT id, name, location_timeout_minutes
        FROM employees 
        WHERE status = 'active' 
        AND is_active = true
        AND (
            last_location_update < cleanup_time - INTERVAL '1 hour' * COALESCE(location_timeout_minutes, 30) / 60
            OR last_location_update IS NULL
        )
    LOOP
        UPDATE employees 
        SET 
            status = 'inactive', 
            auto_checkout_time = cleanup_time,
            updated_at = cleanup_time
        WHERE id = emp_record.id;
        
        INSERT INTO logs (employee_id, action, notes, occurred_at, created_at)
        VALUES (emp_record.id, 'auto_timeout', 'خروج تلقائي - انتهاء المهلة', cleanup_time, cleanup_time);
        
        checkout_count := checkout_count + 1;
    END LOOP;
    
    RETURN json_build_object(
        'success', true,
        'checked_out_count', checkout_count,
        'message', 'تم تسجيل خروج ' || checkout_count || ' موظف تلقائياً',
        'timestamp', cleanup_time,
        'formatted_time', format_iraq_time(cleanup_time)
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION update_employee_password(
    employee_id INTEGER,
    new_password TEXT,
    admin_user_id INTEGER DEFAULT NULL
) RETURNS JSON AS $$
DECLARE
    validation_result JSON;
    update_time TIMESTAMPTZ;
BEGIN
    update_time := NOW();
    
    IF NOT EXISTS (SELECT 1 FROM employees WHERE id = employee_id) THEN
        RETURN json_build_object('success', false, 'error', 'الموظف غير موجود');
    END IF;
    
    SELECT validate_password(new_password) INTO validation_result;
    IF NOT (validation_result->>'valid')::boolean THEN
        RETURN json_build_object('success', false, 'error', validation_result->>'error');
    END IF;
    
    UPDATE employees 
    SET 
        password_hash = hash_password(new_password), 
        password_changed_at = update_time,
        failed_login_attempts = 0, 
        locked_until = NULL,
        updated_at = update_time
    WHERE id = employee_id;
    
    -- تسجيل العملية في main_logs
    INSERT INTO main_logs (action, entity_type, entity_name, latitude, longitude, user_id, occurred_at)
    VALUES ('update', 'password', NULL, NULL, NULL, admin_user_id, update_time);
    
    RETURN json_build_object(
        'success', true, 
        'message', 'تم تحديث كلمة المرور بنجاح',
        'timestamp', update_time
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION unlock_employee_account(employee_id INTEGER, admin_user_id INTEGER DEFAULT NULL) 
RETURNS JSON AS $$
DECLARE
    unlock_time TIMESTAMPTZ;
BEGIN
    unlock_time := NOW();
    
    IF NOT EXISTS (SELECT 1 FROM employees WHERE id = employee_id) THEN
        RETURN json_build_object('success', false, 'error', 'الموظف غير موجود');
    END IF;
    
    UPDATE employees 
    SET 
        failed_login_attempts = 0, 
        locked_until = NULL,
        updated_at = unlock_time
    WHERE id = employee_id;
    
    -- تسجيل العملية في main_logs
    INSERT INTO main_logs (action, entity_type, entity_name, latitude, longitude, user_id, occurred_at)
    VALUES ('unlock', 'account', NULL, NULL, NULL, admin_user_id, unlock_time);
    
    RETURN json_build_object(
        'success', true, 
        'message', 'تم إلغاء قفل الحساب بنجاح',
        'timestamp', unlock_time
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_attendance_total()
RETURNS JSON AS $$
DECLARE
    total_count INTEGER;
BEGIN
    SELECT total INTO total_count FROM attendance_total ORDER BY id LIMIT 1;
    
    IF total_count IS NULL THEN
        INSERT INTO attendance_total (total) VALUES (0);
        total_count := 0;
    END IF;
    
    RETURN json_build_object(
        'success', true,
        'total', total_count
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION reset_attendance_total()
RETURNS JSON AS $$
DECLARE
    reset_time TIMESTAMPTZ;
BEGIN
    reset_time := NOW();
    
    UPDATE attendance_total SET total = 0, updated_at = reset_time;
    
    RETURN json_build_object(
        'success', true,
        'message', 'تم إعادة تعيين العداد الإجمالي',
        'reset_at', reset_time
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ===========================
-- Views والإحصائيات
-- ===========================

CREATE OR REPLACE VIEW employee_stats AS
SELECT 
    e.id,
    e.name,
    e.phone,
    e.position,
    e.status,
    format_iraq_time(e.last_login) as last_login_formatted,
    get_time_ago_arabic(e.last_login) as last_login_ago,
    format_iraq_time(e.last_location_update) as last_location_formatted,
    get_time_ago_arabic(e.last_location_update) as last_location_ago,
    e.failed_login_attempts,
    e.locked_until,
    c.name as center_name,
    c.radius as center_radius,
    (
        SELECT COUNT(*)
        FROM logs l 
        WHERE l.employee_id = e.id 
        AND l.occurred_at >= CURRENT_DATE
    ) as today_logs_count,
    (
        SELECT format_iraq_time(l.occurred_at)
        FROM logs l 
        WHERE l.employee_id = e.id 
        ORDER BY l.occurred_at DESC 
        LIMIT 1
    ) as last_activity_formatted,
    (
        SELECT get_time_ago_arabic(l.occurred_at)
        FROM logs l 
        WHERE l.employee_id = e.id 
        ORDER BY l.occurred_at DESC 
        LIMIT 1
    ) as last_activity_ago
FROM employees e
LEFT JOIN centers c ON e.center_id = c.id
WHERE e.is_active = true
ORDER BY e.last_location_update DESC NULLS LAST;

CREATE OR REPLACE VIEW active_employees_locations AS
SELECT 
    e.id as employee_id,
    e.name as employee_name,
    e.phone,
    e.status,
    format_iraq_time(e.last_location_update) as last_location_formatted,
    get_time_ago_arabic(e.last_location_update) as last_location_ago,
    c.name as center_name,
    l.latitude,
    l.longitude,
    l.accuracy,
    l.action,
    format_iraq_time(l.occurred_at) as occurred_at_formatted,
    get_time_ago_arabic(l.occurred_at) as occurred_at_ago,
    ROW_NUMBER() OVER (PARTITION BY e.id ORDER BY l.occurred_at DESC) as rn
FROM employees e
LEFT JOIN centers c ON e.center_id = c.id
LEFT JOIN logs l ON e.id = l.employee_id AND l.latitude IS NOT NULL
WHERE e.is_active = true
AND e.status = 'active';

-- ===========================
-- Triggers
-- ===========================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'update_employees_updated_at') THEN
        CREATE TRIGGER update_employees_updated_at 
            BEFORE UPDATE ON employees 
            FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'update_centers_updated_at') THEN
        CREATE TRIGGER update_centers_updated_at 
            BEFORE UPDATE ON centers 
            FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'update_users_updated_at') THEN
        CREATE TRIGGER update_users_updated_at 
            BEFORE UPDATE ON users 
            FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'update_attendance_total_updated_at') THEN
        CREATE TRIGGER update_attendance_total_updated_at 
            BEFORE UPDATE ON attendance_total 
            FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
    END IF;
END $$;

-- إضافة الحقول التراكمية
ALTER TABLE centers ADD COLUMN IF NOT EXISTS total_unique_checkins INTEGER DEFAULT 0;
ALTER TABLE centers ADD COLUMN IF NOT EXISTS total_unique_checkouts INTEGER DEFAULT 0;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS total_unique_checkins INTEGER DEFAULT 0;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS total_unique_checkouts INTEGER DEFAULT 0;

-- دالة التريجر
CREATE OR REPLACE FUNCTION increment_unique_checkin()
RETURNS TRIGGER AS $$
BEGIN
    -- أول دخول فريد
    IF (TG_OP = 'INSERT' AND (NEW.action = 'in' OR NEW.action LIKE '%checkin%' OR NEW.action = 'center_entry')) THEN
        IF NOT EXISTS (
            SELECT 1 FROM logs
            WHERE employee_id = NEW.employee_id
              AND center_id = NEW.center_id
              AND (action = 'in' OR action LIKE '%checkin%' OR action = 'center_entry')
              AND id <> NEW.id
        ) THEN
            UPDATE centers SET total_unique_checkins = total_unique_checkins + 1 WHERE id = NEW.center_id;
            UPDATE employees SET total_unique_checkins = total_unique_checkins + 1 WHERE id = NEW.employee_id;
        END IF;
    END IF;
    -- أول خروج فريد
    IF (TG_OP = 'INSERT' AND (NEW.action = 'out' OR NEW.action LIKE '%checkout%')) THEN
        IF NOT EXISTS (
            SELECT 1 FROM logs
            WHERE employee_id = NEW.employee_id
              AND center_id = NEW.center_id
              AND (action = 'out' OR action LIKE '%checkout%')
              AND id <> NEW.id
        ) THEN
            UPDATE centers SET total_unique_checkouts = total_unique_checkouts + 1 WHERE id = NEW.center_id;
            UPDATE employees SET total_unique_checkouts = total_unique_checkouts + 1 WHERE id = NEW.employee_id;
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- تريجر على جدول logs
DROP TRIGGER IF EXISTS trg_increment_unique_checkin ON logs;
CREATE TRIGGER trg_increment_unique_checkin
AFTER INSERT ON logs
FOR EACH ROW
EXECUTE FUNCTION increment_unique_checkin();

-- ===========================
-- الأمان والصلاحيات
-- ===========================

ALTER TABLE employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE centers ENABLE ROW LEVEL SECURITY;
ALTER TABLE logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_center_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance_total ENABLE ROW LEVEL SECURITY;
ALTER TABLE remote_commands ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Enable access for all users" ON centers;
CREATE POLICY "Enable access for all users" ON centers FOR ALL USING (true);

DROP POLICY IF EXISTS "Enable access for all users" ON employees;
CREATE POLICY "Enable access for all users" ON employees FOR ALL USING (true);

DROP POLICY IF EXISTS "Enable access for all users" ON logs;
CREATE POLICY "Enable access for all users" ON logs FOR ALL USING (true);

DROP POLICY IF EXISTS "Enable access for all users" ON users;
CREATE POLICY "Enable access for all users" ON users FOR ALL USING (true);

DROP POLICY IF EXISTS "Enable access for all users" ON user_center_permissions;
CREATE POLICY "Enable access for all users" ON user_center_permissions FOR ALL USING (true);

DROP POLICY IF EXISTS "Enable access for all users" ON attendance_total;
CREATE POLICY "Enable access for all users" ON attendance_total FOR ALL USING (true);

DROP POLICY IF EXISTS "Enable access for all users" ON remote_commands;
CREATE POLICY "Enable access for all users" ON remote_commands FOR ALL USING (true);

GRANT ALL ON TABLE centers TO anon, authenticated;
GRANT ALL ON TABLE employees TO anon, authenticated;
GRANT ALL ON TABLE logs TO anon, authenticated;
GRANT ALL ON TABLE users TO anon, authenticated;
GRANT ALL ON TABLE user_center_permissions TO anon, authenticated;
GRANT ALL ON TABLE attendance_total TO anon, authenticated;
GRANT ALL ON TABLE remote_commands TO anon, authenticated;

GRANT USAGE, SELECT ON SEQUENCE centers_id_seq TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE employees_id_seq TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE logs_id_seq TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE users_id_seq TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE user_center_permissions_id_seq TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE attendance_total_id_seq TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE remote_commands_id_seq TO anon, authenticated;

GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO anon, authenticated;
GRANT SELECT ON employee_stats TO anon, authenticated;
GRANT SELECT ON active_employees_locations TO anon, authenticated;

-- ===========================
-- البيانات التجريبية - حساب مدير مخفي واحد فقط
-- ===========================

DO $$
DECLARE
    center_id_val INTEGER;
    setup_time TIMESTAMPTZ;
BEGIN
    setup_time := NOW();
    
    RAISE NOTICE 'بدء إعداد البيانات التجريبية...';
    
    -- إضافة المركز التجريبي
    INSERT INTO centers (name, longitude, latitude, radius, created_at, updated_at) 
    VALUES ('المركز الرئيسي - كربلاء', 44.0240, 32.6155, 100, setup_time, setup_time)
    RETURNING id INTO center_id_val;
    
    RAISE NOTICE 'تم إضافة المركز التجريبي: %', center_id_val;
    
    -- إضافة العداد الإجمالي
    INSERT INTO attendance_total (total, created_at, updated_at) 
    VALUES (0, setup_time, setup_time);
    
    RAISE NOTICE 'تم إضافة العداد الإجمالي';
    
    -- إضافة المدير المخفي الوحيد
    INSERT INTO users (
        username, password_hash, full_name, email, phone, role,
        can_delete_centers, can_delete_employees, 
        can_view_all_centers, can_view_all_employees,
        is_active, is_hidden,
        created_at, updated_at, password_changed_at
    ) VALUES (
        'admin', 
        crypt('admin123', gen_salt('bf', 12)), 
        'المدير المخفي', 
        'admin@system.com', 
        '07700000000', 
        'admin',
        true, true, true, true, true, true, -- مخفي
        setup_time, setup_time, setup_time
    );
    
    RAISE NOTICE 'تم إضافة المدير المخفي: admin / admin123';
    
EXCEPTION
    WHEN OTHERS THEN
        RAISE NOTICE 'خطأ في إضافة البيانات التجريبية: %', SQLERRM;
END $$;

-- إضافة قيود CHECK على الأعمدة
ALTER TABLE employees DROP CONSTRAINT IF EXISTS valid_iraq_phone;
ALTER TABLE employees ADD CONSTRAINT valid_iraq_phone CHECK (phone ~ '^(077|078|076|075|079)[0-9]{8}$');
ALTER TABLE users DROP CONSTRAINT IF EXISTS valid_iraq_phone_user;
ALTER TABLE users ADD CONSTRAINT valid_iraq_phone_user CHECK (phone IS NULL OR phone ~ '^(077|078|076|075|079)[0-9]{8}$');

-- ===========================
-- تقرير النهائي
-- ===========================

DO $$
DECLARE
    centers_count INTEGER;
    employees_count INTEGER;
    users_count INTEGER;
    visible_users_count INTEGER;
    hidden_users_count INTEGER;
    logs_count INTEGER;
    commands_count INTEGER;
    total_attendance INTEGER;
    report_time TIMESTAMPTZ;
    formatted_time TEXT;
BEGIN
    report_time := NOW();
    formatted_time := format_iraq_time(report_time);
    
    SELECT COUNT(*) INTO centers_count FROM centers;
    SELECT COUNT(*) INTO employees_count FROM employees;
    SELECT COUNT(*) INTO users_count FROM users;
    SELECT COUNT(*) INTO visible_users_count FROM users WHERE is_hidden = false;
    SELECT COUNT(*) INTO hidden_users_count FROM users WHERE is_hidden = true;
    SELECT COUNT(*) INTO logs_count FROM logs;
    SELECT COUNT(*) INTO commands_count FROM remote_commands;
    SELECT total INTO total_attendance FROM attendance_total ORDER BY id LIMIT 1;
    
    RAISE NOTICE '';
    RAISE NOTICE '🎉 تم إعداد نظام الحضور والانصراف الكامل مع حساب مدير مخفي واحد!';
    RAISE NOTICE '===============================================';
    RAISE NOTICE '⏰ وقت الإعداد: % (توقيت العراق)', formatted_time;
    RAISE NOTICE '';
    RAISE NOTICE '📊 إحصائيات النظام:';
    RAISE NOTICE '   🏢 المراكز: %', centers_count;
    RAISE NOTICE '   👤 الموظفين: %', employees_count;
    RAISE NOTICE '   👨‍💼 إجمالي المستخدمين: %', users_count;
    RAISE NOTICE '   👁️ المستخدمين المرئيين: %', visible_users_count;
    RAISE NOTICE '   👻 المستخدمين المخفيين: %', hidden_users_count;
    RAISE NOTICE '   📝 السجلات: %', logs_count;
    RAISE NOTICE '   📡 الأوامر البعيدة: %', commands_count;
    RAISE NOTICE '   📈 العداد الإجمالي: %', COALESCE(total_attendance, 0);
    RAISE NOTICE '';
    RAISE NOTICE '🔑 الحساب المخفي:';
    RAISE NOTICE '===============================================';
    RAISE NOTICE '';
    RAISE NOTICE '👻 المدير المخفي:';
    RAISE NOTICE '   admin / admin123 (مخفي - لا يظهر في الصفحة)';
    RAISE NOTICE '';
    RAISE NOTICE '✨ الميزات المُدمجة:';
    RAISE NOTICE '   ✅ حساب مدير مخفي واحد فقط';
    RAISE NOTICE '   ✅ إضافة المستخدمين من خلال الصفحة';
    RAISE NOTICE '   ✅ عداد الحضور الإجمالي';
    RAISE NOTICE '   ✅ نظام الأوامر البعيدة';
    RAISE NOTICE '   ✅ وظائف الحذف والتعديل المُصححة';
    RAISE NOTICE '   ✅ حذف منطقي للحفاظ على البيانات';
    RAISE NOTICE '   ✅ منع حذف المدير الأخير';
    RAISE NOTICE '   ✅ التحقق من القيود والمراجع';
    RAISE NOTICE '   ✅ توقيت العراق (UTC+3)';
    RAISE NOTICE '   ✅ تنسيق التواريخ بالعربية';
    RAISE NOTICE '   ✅ أمان متقدم وصلاحيات';
    RAISE NOTICE '';
    RAISE NOTICE '🔐 صلاحيات المدير المخفي:';
    RAISE NOTICE '   ✅ جميع العمليات بدون قيود';
    RAISE NOTICE '   ✅ إضافة/تعديل/حذف المراكز والموظفين';
    RAISE NOTICE '   ✅ عرض جميع البيانات والتقارير';
    RAISE NOTICE '   ✅ إضافة المستخدمين الجدد';
    RAISE NOTICE '';
    RAISE NOTICE '🚀 للاختبار السريع:';
    RAISE NOTICE '   المدير المخفي: admin / admin123';
    RAISE NOTICE '';
    RAISE NOTICE '✅ النظام جاهز الآن مع حساب مدير مخفي واحد!';
    RAISE NOTICE '✅ يمكنك إضافة المستخدمين من خلال الصفحة';
    RAISE NOTICE '✅ المدير المخفي لا يظهر في قائمة المستخدمين';
    RAISE NOTICE '✅ جميع كلمات المرور آمنة ومشفرة';
    RAISE NOTICE '✅ النظام يدعم التوقيت العراقي';
    RAISE NOTICE '✅ جميع الميزات المتقدمة مُفعّلة';
    RAISE NOTICE '===============================================';
END $$;

-- استعلام اختبار
SELECT action, entity_type, entity_name, latitude, longitude, user_id, occurred_at FROM main_logs LIMIT 1;
